# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://nicolasmendoza.github.io/
baseurl: /memories/
title: Nicolás
author: Nicolás
description: Apuntes. Personal Blog.
avatar: popota.jpg
email: nicolas.mendoza@yandex.com
github: nicolasmendoza # username
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
